### ISSUE TITLE
GPUSPH compiling-"SetMaxItersSolverSpeed" error

### ISSUE THREAD

**Issue by AlirezaZareii** [GPUSPH/gpusph#79] opened 2023-10-26 17:14 UTC
Hi,
I hope all is well with you.

I compiled Chrono successfully and checked its version using the "git checkout 6.0.0" command. When I compile GPUSPH using the "make chrono=1" command, I receive the following error.

[CC] ProblemCore.osrc/ProblemCore.cc: In member function ‘void ProblemCore::InitializeChrono()’:
src/ProblemCore.cc:192:28: error: ‘class chrono::ChSystem’ has no member named ‘SetMaxItersSolverSpeed’
  m_bodies_physical_system->SetMaxItersSolverSpeed(100);
                            ^~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:985: build/ProblemCore.o] Error 1

Would you please help me to fix the problem?

Regards,
Alireza

**Comment by Oblomov** [comment] 2023-10-26 17:15
Hello @AlirezaZareii, which version of GPUSPH are using?

**Comment by AlirezaZareii** [comment] 2023-10-26 17:18
I used "https://github.com/GPUSPH/gpusph".

**Comment by Oblomov** [comment] 2023-10-26 17:49
There are three branches in the `GPUSPH/gpusph` project repository: `master`, `next` and `spheric2022`. If you are currently using the `master` branch, I recommend checking out the `next` or even better the `spheric2022` branch, that have more up-to-date support for Chrono.

**Comment by AlirezaZareii** [comment] 2023-10-26 18:30
I used the "sphericc2022" branch to compile GPUSPH, but still receive the same error.

**Comment by Oblomov** [comment] 2023-10-27 06:42
Hello, I cannot reproduce this on the `spheric2022`, can you please paste here the output of `make show`?

**Comment by AlirezaZareii** [comment] 2023-10-27 06:48
Yes, sure.

[CONF] make showGPUSPH version:  v5.0+1-08ffd94d
Platform:        Linux
Architecture:    x86_64
Current dir:     /mmfs1/gscratch/derakhti/shared/Alirezaa/gpusph
This Makefile:   /mmfs1/gscratch/derakhti/shared/Alirezaa/gpusph/Makefile
Used Makefiles:   Makefile Makefile.conf Makefile.local dep/command_type.d dep/simframework.d dep/HDF5SphReader.d dep/Integrator.d dep/predcorr_alloc_policy.d dep/base64.d dep/Writer.d dep/ProblemCore.d dep/pugixml.d dep/GPUWorker.d dep/Options.d dep/Synchronizer.d dep/ParticleSystem.d dep/main.d dep/vector_print.d dep/GPUSPH.d dep/VTUReader.d dep/Reader.d dep/buffer_traits.d dep/debugflags.d dep/XYZReader.d dep/cuda/cudautil.d dep/geometries/Vector.d dep/geometries/Cylinder.d dep/geometries/STLMesh.d dep/geometries/Cube.d dep/geometries/Torus.d dep/geometries/Point.d dep/geometries/TopoCube.d dep/geometries/Object.d dep/geometries/Disk.d dep/geometries/EulerParameters.d dep/geometries/Cone.d dep/geometries/Sphere.d dep/geometries/Rect.d dep/geometries/Plane.d dep/integrators/RepackingIntegrator.d dep/integrators/PredictorCorrectorIntegrator.d dep/problem_api/ProblemAPI_1.d dep/writers/UDPWriter.d dep/writers/CustomTextWriter.d dep/writers/CallbackWriter.d dep/writers/CommonWriter.d dep/writers/HotWriter.d dep/writers/VTKWriter.d dep/writers/VTKLegacyWriter.d dep/writers/TextWriter.d dep/writers/HotFile.d dep/NetworkManager.d dep/problems/DamBreak3D.d dep/DamBreak3D.gen.d
Problem:
Linearization:   yzx
Snapshot file:   ./GPUSPH-v5.0+1-08ffd94d-2021-05-29.tgz
Last problem:    DamBreak3D
Sources dir:     src src/adaptors src/cuda src/geometries src/integrators src/problem_api src/problems src/writers
Options dir:     options
Objects dir:     build build/adaptors build/cuda build/geometries build/integrators build/problem_api build/problems build/problems/user build/writers
Scripts dir:     scripts
Docs dir:        docs
Doxygen conf:
Verbose:
Debug:           0
CXX:             g++
CXX version:     g++ (GCC) 8.5.0 20210514 (Red Hat 8.5.0-18)
MPICXX:          g++
nvcc:            /sw/cuda/11.6.2/bin/nvcc -ccbin=g++
nvcc version:    11.6
LINKER:          /sw/cuda/11.6.2/bin/nvcc -ccbin=g++
Compute cap.:    75
Fastmath:        0
USE_MPI:         0
USE_HDF5:        0
USE_CHRONO:      1
default paths:   /usr/include/c++/8 /usr/include/c++/8/x86_64-redhat-linux /usr/include/c++/8/backward /usr/lib/gcc/x86_64-redhat-linux/8/include /usr/local/include /usr/include
INCPATH:         -I /gscratch/derakhti/shared/Alirezaa/gpusph/eigen -Isrc -Isrc/adaptors -Isrc/cuda -Isrc/geometries -Isrc/integrators -Isrc/problem_api -Isrc/problems -Isrc/writers -Isrc/problems -Isrc/problems/user -Ioptions -isystem /mmfs1/gscratch/derakhti/shared/Alirezaa/gpusph/chrono/build -isystem /mmfs1/gscratch/derakhti/shared/Alirezaa/gpusph/chrono/src -isystem /mmfs1/gscratch/derakhti/shared/Alirezaa/gpusph/chrono/src/chrono -isystem /mmfs1/gscratch/derakhti/shared/Alirezaa/gpusph/chrono/src/chrono/collision/bullet
LIBPATH:          -L/usr/local/lib -L/sw/cuda/11.6.2/lib64 -L
LIBS:             -lcudart -lpthread -lrt -lChronoEngine
LDFLAGS:          --linker-options -rpath,  -L/usr/local/lib -L/sw/cuda/11.6.2/lib64 -L -arch=sm_75
CPPFLAGS:        -g -I /gscratch/derakhti/shared/Alirezaa/gpusph/eigen -Isrc -Isrc/adaptors -Isrc/cuda -Isrc/geometries -Isrc/integrators -Isrc/problem_api -Isrc/problems -Isrc/writers -Isrc/problems -Isrc/problems/user -Ioptions -isystem /mmfs1/gscratch/derakhti/shared/Alirezaa/gpusph/chrono/build -isystem /mmfs1/gscratch/derakhti/shared/Alirezaa/gpusph/chrono/src -isystem /mmfs1/gscratch/derakhti/shared/Alirezaa/gpusph/chrono/src/chrono -isystem /mmfs1/gscratch/derakhti/shared/Alirezaa/gpusph/chrono/src/chrono/collision/bullet -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -D_GLIBCXX_USE_C99_MATH -DUSE_HDF5=0 -D__COMPUTE__=75
CXXFLAGS:        -std=c++14 -march=native -m64 -std=c++11 -O3
CUFLAGS:          -arch=sm_75 --generate-line-info -std=c++14 -std=c++11 --compiler-options -march=native,-m64,-O3

**Comment by Oblomov** [comment] 2023-10-27 07:00
From the output of `make show` it seems you are *not* using the `spheric2022` branch.  Can you please try again making sure that you are on the correct branch? You can also check it out on a separate directory by cloning it as:

    git clone https://github.com/GPUSPH/gpusph gpusph-spheric2022 -b spheric2022

**Comment by vitozago** [comment] 2023-10-27 14:37
Hello @AlirezaZareii, I've read the conversation above, together with @Oblomov suggestions, also make sure that you compile Chrono after you check out its version 6.0.0

**Comment by Oblomov** [comment] 2024-02-15 22:01
Hello @AlirezaZareii do you still have this issue? If not, can we close this?

**Comment by AlirezaZareii** [comment] 2024-02-15 22:03
Hi, 
Using spheric2022 solved the problem. We can close this. Thanks.

**Closed as completed** 2024-02-16 07:28 UTC
