### ISSUE TITLE
How to report website errors/bugs

### ISSUE THREAD

**Issue by saltynexus** [GPUSPH/gpusph#57] opened 2019-10-16 02:57 UTC
I was just over on the website ( www.gpusph.org ), trying to reach the "Discourse group" and I found that the link is broken ( https://gpusph.discourse.group/ ). Obviously that is an issue that needs to be fixed, but it also raises the question....who are we suppose to report errors/bugs to with regards to the website? I don't even know if the people here on Github are responsible for the website? Nevertheless, I figured someone here would have some insight.

**Comment by Oblomov** [comment] 2019-10-16 07:06
This is a good place to report website issues as well, and thanks for reporting it. The issue isn't that the link is broken, but that for some reason the Discourse group was reset … I will contact the Discourse team about it, thanks.

**Comment by saltynexus** [comment] 2019-10-21 22:17
I closed this 5days ago, thinking it would be taken care but I'm finding that the Discourse is still down. Is there any update on the status?

**Comment by Oblomov** [comment] 2019-10-22 05:05
The last update I have is from Friday, and they're still working on it … not sure why it's taking so long.

Keep this open, I'll close it when I get notification from the hosting company that it's back up.

**Comment by Oblomov** [comment] 2019-10-26 06:03
OK, it seems the forum was restored, sorry for the downtime!

**Closed by Oblomov** 2019-10-26 06:03 UTC
